[32mINFO    [0m root:test_login.py:44 ****************verifying Login Test*************** 
[1m[31mERROR   [0m root:test_login.py:63 **************Login Test failed**************